#!/usr/bin/python
import pyaudio
import wave
import time
import sys

import png

# define callback (2)
def callback(in_data, frame_count, time_info, status):

    print timeinfo
    data = []
    for i in xrange(frame_count):
        data.append(0)
    return (data, pyaudio.paContinue)


def main():
    # instantiate PyAudio (1)
    p = pyaudio.PyAudio()


    # open stream using callback (3)
    stream = p.open(format=p.get_format_from_width(wf.getsampwidth()),
                    channels=wf.getnchannels(),
                    rate=wf.getframerate(),
                    output=True,
                    stream_callback=callback)

    # start the stream (4)
    stream.start_stream()

    # wait for stream to finish (5)
    while stream.is_active():
        time.sleep(0.1)

    # stop stream (6)
    stream.stop_stream()
    stream.close()
    wf.close()

    # close PyAudio (7)
    p.terminate()

if __name__ == '__main__':
    main()
